name: Keep Repository Active

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  keep-repository-active:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

      - name: Create Keep Alive Marker
        run: |
          mkdir -p .github/logs
          echo "Repository active as of $(date)" > .github/logs/keep_alive.log

      - name: Commit Changes
        run: |
          git add .github/logs/keep_alive.log
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "🤖 Keep repository active: $(date +"%Y-%m-%d %H:%M:%S")"
            git push
          fi

      - name: Log Workflow Status
        if: always()
        run: echo "Workflow completed at $(date)"
